### ISSUE TITLE
Save e-mail on profile for registration via Microsoft

### ISSUE THREAD

**Issue by Weyl1** [Azuriom/Azuriom#350] opened 2023-07-09 15:57 UTC
### Description of your suggestion

Hello, 
Doesn't the microsoft connection allow you to register your email address directly? It's a bit annoying that players have to go to their profile to add an email address and then check it, and don't receive an email verification notification when they first log in.

**Comment by MrMicky-FR** [comment] 2023-07-09 16:33
Duplicate of #328

**Closed by MrMicky-FR** 2023-07-09 16:33 UTC
Labels: duplicate
