### ISSUE TITLE
Auto translation

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#306] opened 2023-02-21 12:09 UTC
### Description of your suggestion

Add and the option to change the language (every user can change it) that auto changes the language of the website depending on the country of the ip.

### Advantages

Universal websites in terms of languages, actually you can only have one active language.

**Comment by MrMicky-FR** [comment] 2023-02-21 12:30
Duplicate of #242 

(And on a side note, using IP address for language detection is a really bad idea as lot of countries speak multiples languages, the browser language header should be used instead)

**Closed by MrMicky-FR** 2023-02-21 12:30 UTC

**Comment by Jotiprime** [comment] 2023-02-21 12:55
Okay, at least allow end user to change the language.

**Comment by MrMicky-FR** [comment] 2023-02-21 13:19
[My comment](https://github.com/Azuriom/Azuriom/issues/242#issuecomment-1289121524) would unfortunately still be valid
