### ISSUE TITLE
New users are logged-in when registering while maintenance mode on (Steam)

### ISSUE THREAD

**Issue by Certurix** [Azuriom/Azuriom#287] opened 2023-01-20 10:38 UTC
### Bug Description

When you try to access the Support page while logged out with the Steam Version of Azuriom, the website will redirect you to Steam authentification to be logged in the website. However, if you were not registered before, the plugin makes the user be registered on the database and on the admin panel in /admin/users

The user will be redirected to Steam website after this action.

## Steps to reproduce

1. Access your website as non logged user. The Steam user must not be an admin!
2. Try to login with the Support page (yourdomain.com/support/tickets)
3. Authorize Steam login
4. You'll be redirected on Steam page but your account will be registered on database and in admin panel.

### Error Logs
None

### Additional Context
Tested only on AzuriomCoud, may test it on self-hosted website.

**Comment by MrMicky-FR** [comment] 2023-01-20 11:06
Seems like the issue isn’t related to the support plugin, but is instead for users registered while maintenance is enabled

**Comment by MrMicky-FR** [comment] 2023-02-05 18:51
Fixed in https://github.com/Azuriom/Azuriom/commit/ae75ff78735b159f069df539e94578d0cf0ea339

**Closed by MrMicky-FR** 2023-02-05 18:51 UTC
