### ISSUE TITLE
Add icon support for navbar tabs

### ISSUE THREAD

**Issue by Doncellup** [Azuriom/Azuriom#200] opened 2022-08-22 16:27 UTC
You should add a category icon like this :
![image](https://user-images.githubusercontent.com/90469321/185970873-57ab509c-ef5f-4567-8221-444aabe5cf35.png)

Which would give the possibility to do this :
![image](https://user-images.githubusercontent.com/90469321/185971325-cf19ee8f-a406-48eb-ac0d-d27319150dee.png)

**Comment by MrMicky-FR** [comment] 2022-08-22 17:34
Already supported, duplicate of #199

**Closed by MrMicky-FR** 2022-08-22 17:34 UTC
Labels: duplicate
