### ISSUE TITLE
Add a generic asset name Azuriom.zip in releases to make download easier

### ISSUE THREAD

**Issue by magrigry** [Azuriom/Azuriom#96] opened 2021-09-14 17:46 UTC
Downloads would be much easier if assets does not contain the release name
We could simply use `https://github.com/Azuriom/Azuriom/releases/latest/download/Azuriom.zip`
It would avoid quering the API to get the download URI (for example within the [installer](https://github.com/Azuriom/AzuriomInstaller)

This simplification request is related to a user that encoutered a 403 forbidden from github API (see discussion [here](https://discord.com/channels/625774284823986183/625777292052004916/887374128754069535)) while using the [installer](https://github.com/Azuriom/AzuriomInstaller)
![image](https://cdn.discordapp.com/attachments/625777292052004916/887374126430449714/unknown.png)

**Comment by MrMicky-FR** [comment] 2021-09-19 23:17
Using version in assets name is a standard practice, but we will replace (back) this usage of the GitHub API with our own API to prevent this issue, even though this is certainly caused by an issue with the user setup as this seems like related to rate limitation.

**Comment by MrMicky-FR** [comment] 2022-01-25 19:49
Fixed with https://github.com/Azuriom/AzuriomInstaller/commit/71dc89173f7091f89b2bb7ccc3bd38f015485dcc

**Closed by MrMicky-FR** 2022-01-25 19:49 UTC
Labels: enhancement
