### ISSUE TITLE
Add the ability to Sync Roles between Discord and Azuriom

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Azuriom#288] opened 2023-01-29 16:42 UTC
### Description of your suggestion

Add Discord synchronization with Azuriom, so the roles will be given automatically without users having to open a ticket to receive the role.

### Advantages

Users will receive the role automatically on Discord.

**Comment by MrMicky-FR** [comment] 2023-01-29 17:13
Duplicate of #254

**Closed by MrMicky-FR** 2023-01-29 17:13 UTC
