### ISSUE TITLE
Error: The connection to the server failed: GetInfo: Packet header mismatch. (0x41)

### ISSUE THREAD

**Issue by DunklerKeksYT** [Azuriom/Azuriom#115] opened 2021-12-20 20:21 UTC
Hello Pls Help
The Ports are all Online and open

**Comment by MrMicky-FR** [comment] 2021-12-20 20:26
Duplicate of #114

**Closed by MrMicky-FR** 2021-12-20 20:26 UTC

**Comment by MrMicky-FR** [comment] 2021-12-22 20:35
See https://github.com/Azuriom/Azuriom/issues/114#issuecomment-999855835 for a quick fix
