### ISSUE TITLE
Improvements to the language option

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Azuriom#435] opened 2024-03-31 18:46 UTC
### Description of your suggestion

Currently, when we select the website language, it changes both in the admin panel and for the user.

It would be interesting to have two options, change the language I want to use in the admin panel and change the language only for the website for users.

It was an option for the user to choose the language for themselves on the website.

### Advantages

I believe that this way users have the freedom to choose their preferred language.

**Comment by MrMicky-FR** [comment] 2024-03-31 18:58
Duplicate of #242

**Closed by MrMicky-FR** 2024-03-31 18:58 UTC
Labels: duplicate
