### ISSUE TITLE
Support for multiple Steam Games in Servers

### ISSUE THREAD

**Issue by Ventrex** [Azuriom/Azuriom#389] opened 2023-10-02 09:25 UTC
### Description of your suggestion

Currently you can choose 1 game but you cannot easly change it or add more games to it.

Now I need to create a sub domain and relink everything to that game, but then people need to create a new account to that one to, also very difficult to make default text and copy paste them to all domains.

Is it possible to add multi game server support, for communities who also have other games?
In our community we love azuriom, but we started with RUST, and now we also have minecraft, ark and thinking about Hurtworld, but main website still points to RUST.

It is not that everything needs to be changed, but in de Admin Panel under servers, add option to add other games to.

For example,
- Press Add Server button
- Question for which game
- Depending on the game you choose, get the settings for that game.

### Advantages

For communities with multiple games can also start using Azuriom
Also when the game has been changed in an community not the whole site needs to be remade.

**Comment by MrMicky-FR** [comment] 2023-10-02 09:32
Duplicate of #222

**Closed by MrMicky-FR** 2023-10-02 09:32 UTC
