### ISSUE TITLE
Add Google sing in

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Azuriom#358] opened 2023-08-15 22:58 UTC
### Description of your suggestion

Will be good to have google Sing in in the next update. Google

### Advantages

People don't need to remember more passwords, more secure.

**Comment by naekaa444** [comment] 2023-08-15 23:09
I've already made the proposal and it was refused.
Google privacy really sucks.

I've made a GoogleAuth plugin that's available on my GitHub if you're interested anyway.

**Comment by MrMicky-FR** [comment] 2023-08-15 23:28
Duplicate of #324, which seems to be your own suggestion !??

**Closed by MrMicky-FR** 2023-08-15 23:28 UTC
Labels: duplicate
